[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=61",
  "wheel",
  "setuptools-scm>=8",
    "numpy>=1.22",
    "xarray>=2023.1",
    "xclim>=0.59.1",
    "earthkit-data>=0.17.0"
]

[project]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering"
]
dependencies = [
  "numpy>=1.22",
  "xarray>=2023.1",
  "xclim>=0.59.1",
  "xsdba>=0.5,<0.6",
  "earthkit-data>=0.17.0"
]
description = "Aggregation tools for meteorological and climate data."
dynamic = ["version"]
keywords = ["climate", "meteorology", "geospatial", "analysis", "earthkit"]
license = {file = "LICENSE"}
name = "earthkit-climate"
readme = "README.md"
requires-python = ">=3.10,<3.13"

[project.optional-dependencies]
dev = ["black", "ruff", "mypy", "pre-commit", "make", "ipython"]
docs = ["sphinx", "sphinx-rtd-theme", "sphinx-autoapi", "nbsphinx"]

[tool.black]
line-length = 110

[tool.coverage.run]
branch = true

[tool.isort]
profile = "black"
line_length = 110

[tool.pixi.dependencies]
pixi-pycharm = ">=0.0.9,<0.0.10"
pytest = "*"
pytest-cov = "*"
pytest-mock = ">=3.15.1,<4"
python = "3.12.*"
ipykernel = ">=7.1.0,<8"

# ---- Pixi environments ----
[tool.pixi.environments]
dev = {features = ["dev"]}
docs = {features = ["docs"]}

[tool.pixi.pypi-dependencies]
earthkit-plots = ">=0.5.0"

# ---- Pixi CONFIGURATION ----
[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tool.pytest.ini_options]
addopts = "-vv --cov=. --cov-report=html --doctest-glob='*.md' --doctest-glob='*.rst'"

[tool.ruff]
ignore = [
  "D1",  # pydocstyle: Missing Docstrings
  "D107",  # pydocstyle: numpy convention
  "D203",
  "D205",
  "D212",
  "D213",
  "D401",
  "D402",
  "D413",
  "D415",
  "D416",
  "D417"
]
line-length = 110
select = [
  "F",  # pyflakes
  "E",  # pycodestyle
  "W",  # pycodestyle warnings
  "I",  # isort
  "D"  # pydocstyle
]

# ---- Namespace package configuration ----
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
write_to = "src/earthkit/climate/version.py"
write_to_template = '''
# Do not change! Do not track in version control!
__version__ = "{version}"
'''
