[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]

[project]
name = "earthkit-climate"
description = "Aggregation tools for meteorological and climate data."
readme = "README.md"
license = { file = "LICENSE" }
dynamic = ["version"]
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering"
]
dependencies = [
  "xarray>=2022.3.0",
  "numpy>=1.18",
  "geopandas"
]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
docs = ["sphinx", "sphinx-rtd-theme", "sphinx-autoapi", "nbsphinx"]
development = ["black", "ruff", "mypy", "pre-commit", "make", "ipython"]

[tool.coverage.run]
branch = true

[tool.ruff]
ignore = [
  "D1",      # pydocstyle: Missing Docstrings
  "D107",    # pydocstyle: numpy convention
  "D203",
  "D205",
  "D212",
  "D213",
  "D401",
  "D402",
  "D413",
  "D415",
  "D416",
  "D417"
]
line-length = 110
select = [
  "F",  # pyflakes
  "E",  # pycodestyle
  "W",  # pycodestyle warnings
  "I",  # isort
  "D"   # pydocstyle
]

# ---- Namespace package configuration ----
[tool.setuptools.packages.find]
where = ["src"]
namespaces = true

[tool.setuptools_scm]
write_to = "src/earthkit/climate/version.py"
write_to_template = '''
# Do not change! Do not track in version control!
__version__ = "{version}"
'''

# ---- PIXI CONFIGURATION ----
[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tool.pixi.dependencies]
python = "3.12.*"
numpy = "*"
xarray = "*"
geopandas = "*"
xclim = "*"
pip = "*"
xsdba = ">=0.5.0,<0.6"
pixi-pycharm = ">=0.0.9,<0.0.10"

[tool.pixi.pypi-dependencies]
earthkit-data = ">=0.17.0"

# ---- Pixi environments ----
[tool.pixi.environments]
default = {features = [], solve-group = "default"}
test = {features = ["test"], solve-group = "default"}
docs = {features = ["docs"], solve-group = "default"}
development = {features = ["development"], solve-group = "default"}

# ---- Optional post-install cleanup ----
[tool.pixi.tasks]
remove-init = { cmd = "rm -f $(python -c 'import site; print(site.getsitepackages()[0])')/earthkit/__init__.py || true" }

[tool.pixi.tasks.post-install]
depends-on = ["remove-init"]